[theme]

# The preset Streamlit theme that your custom theme inherits from.
# One of "light" or "dark".
# base =

# Primary accent color for interactive elements.
# The value below was set in G:\CURSOS\Python\mini_projects\LitteraGPT\.streamlit\config.toml
primaryColor = "#566573"

# Background color for the main content area.
backgroundColor = '#ffffff'

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = '#ffefe0'

# Color used for almost all text.
textColor = '#566573'

# Font family for all text in the app, except code blocks. One of "sans serif",
# "serif", or "monospace".
# font =